// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/payment/v1/payment.proto

package paymentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentState int32

const (
	PaymentState_PAYMENT_STATE_UNSPECIFIED PaymentState = 0
	PaymentState_PAYMENT_STATE_INITIATED   PaymentState = 1
	PaymentState_PAYMENT_STATE_PENDING     PaymentState = 2
	PaymentState_PAYMENT_STATE_CAPTURED    PaymentState = 3
	PaymentState_PAYMENT_STATE_FAILED      PaymentState = 4
)

// Enum value maps for PaymentState.
var (
	PaymentState_name = map[int32]string{
		0: "PAYMENT_STATE_UNSPECIFIED",
		1: "PAYMENT_STATE_INITIATED",
		2: "PAYMENT_STATE_PENDING",
		3: "PAYMENT_STATE_CAPTURED",
		4: "PAYMENT_STATE_FAILED",
	}
	PaymentState_value = map[string]int32{
		"PAYMENT_STATE_UNSPECIFIED": 0,
		"PAYMENT_STATE_INITIATED":   1,
		"PAYMENT_STATE_PENDING":     2,
		"PAYMENT_STATE_CAPTURED":    3,
		"PAYMENT_STATE_FAILED":      4,
	}
)

func (x PaymentState) Enum() *PaymentState {
	p := new(PaymentState)
	*p = x
	return p
}

func (x PaymentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_payment_v1_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentState) Type() protoreflect.EnumType {
	return &file_proto_payment_v1_payment_proto_enumTypes[0]
}

func (x PaymentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentState.Descriptor instead.
func (PaymentState) EnumDescriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

type CreatePaymentIntentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	AmountInCents  int64                  `protobuf:"varint,2,opt,name=amount_in_cents,json=amountInCents,proto3" json:"amount_in_cents,omitempty"`
	Currency       string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	OrderId        string                 `protobuf:"bytes,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePaymentIntentRequest) Reset() {
	*x = CreatePaymentIntentRequest{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentRequest) ProtoMessage() {}

func (x *CreatePaymentIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentIntentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetAmountInCents() int64 {
	if x != nil {
		return x.AmountInCents
	}
	return 0
}

func (x *CreatePaymentIntentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CreatePaymentIntentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentId      string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	State          PaymentState           `protobuf:"varint,2,opt,name=state,proto3,enum=payment.v1.PaymentState" json:"state,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePaymentIntentResponse) Reset() {
	*x = CreatePaymentIntentResponse{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentResponse) ProtoMessage() {}

func (x *CreatePaymentIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentIntentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreatePaymentIntentResponse) GetState() PaymentState {
	if x != nil {
		return x.State
	}
	return PaymentState_PAYMENT_STATE_UNSPECIFIED
}

func (x *CreatePaymentIntentResponse) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

var File_proto_payment_v1_payment_proto protoreflect.FileDescriptor

const file_proto_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/payment/v1/payment.proto\x12\n" +
	"payment.v1\"\xa4\x01\n" +
	"\x1aCreatePaymentIntentRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12&\n" +
	"\x0famount_in_cents\x18\x02 \x01(\x03R\ramountInCents\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x19\n" +
	"\border_id\x18\x04 \x01(\tR\aorderId\"\x95\x01\n" +
	"\x1bCreatePaymentIntentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12.\n" +
	"\x05state\x18\x02 \x01(\x0e2\x18.payment.v1.PaymentStateR\x05state\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey*\x9b\x01\n" +
	"\fPaymentState\x12\x1d\n" +
	"\x19PAYMENT_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PAYMENT_STATE_INITIATED\x10\x01\x12\x19\n" +
	"\x15PAYMENT_STATE_PENDING\x10\x02\x12\x1a\n" +
	"\x16PAYMENT_STATE_CAPTURED\x10\x03\x12\x18\n" +
	"\x14PAYMENT_STATE_FAILED\x10\x042x\n" +
	"\x0ePaymentService\x12f\n" +
	"\x13CreatePaymentIntent\x12&.payment.v1.CreatePaymentIntentRequest\x1a'.payment.v1.CreatePaymentIntentResponseB;Z9github.com/johncegom/stratapay/proto/payment/v1;paymentv1b\x06proto3"

var (
	file_proto_payment_v1_payment_proto_rawDescOnce sync.Once
	file_proto_payment_v1_payment_proto_rawDescData []byte
)

func file_proto_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_proto_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_proto_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payment_v1_payment_proto_rawDesc), len(file_proto_payment_v1_payment_proto_rawDesc)))
	})
	return file_proto_payment_v1_payment_proto_rawDescData
}

var file_proto_payment_v1_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_payment_v1_payment_proto_goTypes = []any{
	(PaymentState)(0),                   // 0: payment.v1.PaymentState
	(*CreatePaymentIntentRequest)(nil),  // 1: payment.v1.CreatePaymentIntentRequest
	(*CreatePaymentIntentResponse)(nil), // 2: payment.v1.CreatePaymentIntentResponse
}
var file_proto_payment_v1_payment_proto_depIdxs = []int32{
	0, // 0: payment.v1.CreatePaymentIntentResponse.state:type_name -> payment.v1.PaymentState
	1, // 1: payment.v1.PaymentService.CreatePaymentIntent:input_type -> payment.v1.CreatePaymentIntentRequest
	2, // 2: payment.v1.PaymentService.CreatePaymentIntent:output_type -> payment.v1.CreatePaymentIntentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_payment_v1_payment_proto_init() }
func file_proto_payment_v1_payment_proto_init() {
	if File_proto_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_v1_payment_proto_rawDesc), len(file_proto_payment_v1_payment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_proto_payment_v1_payment_proto_depIdxs,
		EnumInfos:         file_proto_payment_v1_payment_proto_enumTypes,
		MessageInfos:      file_proto_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_proto_payment_v1_payment_proto = out.File
	file_proto_payment_v1_payment_proto_goTypes = nil
	file_proto_payment_v1_payment_proto_depIdxs = nil
}
